let n
export let { dashVendor,
    capVendor,
    all,
    has,
    badCSS,
    vendor,
    importFont,
    toCaps,
    toDash,
    toCSS,
    registerCSS,
    registerCSSRaw,
    formatStr,
    importCSS,
    getDefaultStyleSheet,
    reducedMotion,
    registerCSSAll,
    supportsRule,
    pcv,
    supportedPClassVendor,
    pev,
    supportedPElementVendor,
    dropShadow,
    boxShadow } = Symbol.for('CSS') in Object(window.css) ? css : (await import('./css.js'), n=css, delete window.css, n)