debugger
let sym = Symbol.for('CSS')
export let { dashVendor,
    capVendor,
    all,
    has,
    badCSS,
    vendor,
    importFont,
    toCaps,
    toDash,
    toCSS,
    registerCSS,
    registerCSSRaw,
    formatStr,
    importCSS,
    getDefaultStyleSheet,
    reducedMotion,
    registerCSSAll,
    supportsRule,
    pcv,
    supportedPClassVendor,
    pev,
    supportedPElementVendor,
    dropShadow,
    boxShadow } = sym in window ? window[sym] : (await import('./css.js'),window[sym])
// delete window[sym]